version: '3'

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./certs:/etc/nginx/certs
        links:
            - nodejs:nodejs
        depends_on:
            - nodejs
        ports:
            - "8080:80"
            - "8083:443"
        networks:
            - app-network

    couchdb:
        image: couchdb
        networks:
            - app-network
        environment:
            - COUCHDB_USER=admin
            - COUCHDB_PASSWORD=admin
        volumes:
            - "./couchdb:/opt/couchdb/data"
        ports:
            - "5984:5984"
        restart: on-failure

    nodejs:
        build:
            context: ./src
        ports:
            - "3000:3000"
        depends_on:
            - couchdb
        links:
            - couchdb  
        volumes:
            - ./src:/src/
        networks:
            - app-network
        restart: on-failure


volumes:
    couchdb-data:


networks:
    app-network:
        driver: bridge
        