version: '3'

services:

    couchdb:
        image: "couchdb"
        networks:
            - app-network
        environment:
            - COUCHDB_USER=admin
            - COUCHDB_PASSWORD=admin
        volumes:
            - "./couchdb:/opt/couchdb/data"
        ports:
            - "5984:5984"
        restart: on-failure

    nodejs:
        build: "./src"
        ports:
            - "3000:3000"
        depends_on:
            - couchdb
        links:
            - couchdb  
        volumes:
            - ./src:/src/
        networks:
            - app-network
        restart: on-failure


volumes:
    couchdb-data:


networks:
    app-network:
        driver: bridge
        
        