name: CI/CD
on:
  push:
    branches: [ main ]
jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm install -g mocha
      - run: npm install --prefix ./src
      - run: npm test
