name: CI/CD
on:
  push:
    branches: [ main ]
jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:
      # Step 1
      - name: Checkout
        uses: actions/checkout@v2

      # Step 2
      - name: Start containers 
        run: docker-compose up -d 

      # Step 3
      - name: Install node
        uses: actions/setup-node@v2

      # Step 4
      - name: Install mocha
        run: npm install -g mocha

      # Step 5
      - name: Install dependencies 
        run: npm install --prefix ./src
  
      # Step 6
      - name: Run Test
        run: npm test --prefix ./src

      # Step 7
      - name: Stop containers
        if: always() 
        run: docker-compose down
